print(Person);
local p = Person:createPerson();
print(p);
print(p.name);
p.name = {a=2};
print(p.name);
p.value = "test value";
print(p.value);
p.intValue = 2222;
print(p.intValue);
p:speak("Hello");
